'use client'
import * as React from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Separator } from '@/components/ui/separator'
import { Badge } from '@/components/ui/badge'
import { toast } from 'sonner'
import { Field, ResultBox, randomInt } from '@/lib/tools/tool-ui'
type DefaultRule = 'allow' | 'disallow'
type PathRule = 'allow' | 'disallow'
interface CustomRule {
  id: string
  userAgent: string
  rules: { path: string; type: PathRule }[]
}
function uid(): string {
  return `r-${Date.now().toString(36)}-${randomInt(1_000_000).toString(36)}`
}
function buildRobots(
  sitemap: string,
  defaultRule: DefaultRule,
  rules: CustomRule[]
): string {
  const lines: string[] = []
  lines.push('# robots.txt — generated by Fernandes Labs')
  lines.push('')
  // Default rule for all bots
  lines.push('User-agent: *')
  if (defaultRule === 'allow') {
    lines.push('Allow: /')
  } else {
    lines.push('Disallow: /')
  }
  lines.push('')
  // Custom rules
  for (const rule of rules) {
    const ua = rule.userAgent.trim()
    if (!ua) continue
    lines.push(`User-agent: ${ua}`)
    if (rule.rules.length === 0) {
      lines.push('Allow: /')
    } else {
      for (const r of rule.rules) {
        const path = r.path.trim()
        if (!path) continue
        const label = r.type === 'allow' ? 'Allow' : 'Disallow'
        lines.push(`${label}: ${path}`)
      }
    }
    lines.push('')
  }
  if (sitemap.trim()) {
    lines.push(`Sitemap: ${sitemap.trim()}`)
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n'
}
function CustomRuleCard({
  rule,
  onChange,
  onRemove,
}: {
  rule: CustomRule
  onChange: (next: CustomRule) => void
  onRemove: () => void
}): React.JSX.Element {
  const updateRule = (idx: number, patch: Partial<{ path: string; type: PathRule }>): void => {
    const nextRules = rule.rules.map((r, i) => (i === idx ? { ...r, ...patch } : r))
    onChange({ ...rule, rules: nextRules })
  }
  const addPath = (): void => {
    onChange({
      ...rule,
      rules: [...rule.rules, { path: '/', type: 'disallow' }],
    })
  }
  const removePath = (idx: number): void => {
    onChange({ ...rule, rules: rule.rules.filter((_, i) => i !== idx) })
  }
  return (
    <div className="rounded-lg border border-border bg-card p-3">
      <div className="flex items-center gap-2">
        <Input
          aria-label="User-agent"
          value={rule.userAgent}
          onChange={(e) => onChange({ ...rule, userAgent: e.target.value })}
          placeholder="Googlebot"
        />
        <Button
          type="button"
          variant="ghost"
          size="icon"
          onClick={onRemove}
          aria-label="Remove rule"
        >
          <Trash2 className="size-4" />
        </Button>
      </div>
      <div className="mt-3 space-y-2">
        {rule.rules.length === 0 ? (
          <p className="text-xs text-muted-foreground">
            No path rules yet — defaults to allow all.
          </p>
        ) : (
          rule.rules.map((r, i) => (
            <div key={i} className="flex items-center gap-2">
              <RadioGroup
                value={r.type}
                onValueChange={(v) => updateRule(i, { type: v as PathRule })}
                className="flex flex-row gap-3"
              >
                <div className="flex items-center gap-1.5">
                  <RadioGroupItem value="allow" id={`${rule.id}-a-${i}`} />
                  <Label htmlFor={`${rule.id}-a-${i}`} className="text-xs">
                    Allow
                  </Label>
                </div>
                <div className="flex items-center gap-1.5">
                  <RadioGroupItem value="disallow" id={`${rule.id}-d-${i}`} />
                  <Label htmlFor={`${rule.id}-d-${i}`} className="text-xs">
                    Disallow
                  </Label>
                </div>
              </RadioGroup>
              <Input
                aria-label="Path"
                value={r.path}
                onChange={(e) => updateRule(i, { path: e.target.value })}
                placeholder="/private/"
                className="flex-1"
              />
              <Button
                type="button"
                variant="ghost"
                size="icon"
                onClick={() => removePath(i)}
                aria-label="Remove path"
              >
                <Trash2 className="size-3.5" />
              </Button>
            </div>
          ))
        )}
      </div>
      <Button type="button" variant="outline" size="sm" className="mt-2" onClick={addPath}>
        <Plus className="size-3.5" />
        Add path
      </Button>
    </div>
  )
}
export default function RobotsTxtGenerator(): React.JSX.Element {
  const [sitemap, setSitemap] = React.useState('')
  const [defaultRule, setDefaultRule] = React.useState<DefaultRule>('allow')
  const [rules, setRules] = React.useState<CustomRule[]>([])
  const addRule = (): void => {
    setRules((prev) => [
      ...prev,
      { id: uid(), userAgent: '', rules: [{ path: '/', type: 'disallow' }] },
    ])
  }
  const updateRule = (id: string, next: CustomRule): void => {
    setRules((prev) => prev.map((r) => (r.id === id ? next : r)))
  }
  const removeRule = (id: string): void => {
    setRules((prev) => prev.filter((r) => r.id !== id))
  }
  const output = React.useMemo(
    () => buildRobots(sitemap, defaultRule, rules),
    [sitemap, defaultRule, rules]
  )
  const reset = (): void => {
    setSitemap('')
    setDefaultRule('allow')
    setRules([])
    toast.success('Form reset')
  }
  return (
    <div className="space-y-5">
      <Card>
        <CardHeader>
          <CardTitle>Robots.txt Generator</CardTitle>
          <CardDescription>
            Compose a valid <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">robots.txt</code>{' '}
            with a default rule for all bots, custom per-user-agent rules, and a
            sitemap directive.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Field label="Sitemap URL" htmlFor="rt-sitemap">
            <Input
              id="rt-sitemap"
              value={sitemap}
              onChange={(e) => setSitemap(e.target.value)}
              placeholder="https://example.com/sitemap.xml"
              type="url"
            />
          </Field>
          <Field label="Default rule (User-agent: *)" htmlFor="rt-default">
            <RadioGroup
              id="rt-default"
              value={defaultRule}
              onValueChange={(v) => setDefaultRule(v as DefaultRule)}
              className="flex flex-row gap-6"
            >
              <div className="flex items-center gap-2">
                <RadioGroupItem value="allow" id="rt-allow" />
                <Label htmlFor="rt-allow">Allow all</Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="disallow" id="rt-disallow" />
                <Label htmlFor="rt-disallow">Disallow all</Label>
              </div>
            </RadioGroup>
          </Field>
          <Separator />
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-medium text-foreground">
                Custom user-agent rules
              </h3>
              <p className="text-xs text-muted-foreground">
                Override the default for specific crawlers.
              </p>
            </div>
            <Button type="button" variant="outline" size="sm" onClick={addRule}>
              <Plus className="size-3.5" />
              Add rule
            </Button>
          </div>
          {rules.length === 0 ? (
            <p className="rounded-lg border border-dashed border-border p-4 text-center text-xs text-muted-foreground">
              No custom rules. The default rule above applies to all crawlers.
            </p>
          ) : (
            <div className="space-y-2">
              {rules.map((r) => (
                <CustomRuleCard
                  key={r.id}
                  rule={r}
                  onChange={(next) => updateRule(r.id, next)}
                  onRemove={() => removeRule(r.id)}
                />
              ))}
            </div>
          )}
          <div className="flex items-center gap-2">
            <Button type="button" variant="outline" size="sm" onClick={reset}>
              Reset
            </Button>
            <Badge variant="secondary">{rules.length} custom rules</Badge>
          </div>
        </CardContent>
      </Card>
      <ResultBox
        value={output}
        label="robots.txt"
        downloadName="robots.txt"
        rows={12}
        empty="Add a sitemap URL or custom rules to begin."
      />
    </div>
  )
}