import sharp from 'sharp'
import { getToolMeta } from '@/lib/tools/tool-meta'
import { CATEGORY_META, type ToolCategory } from '@/lib/tools/types'
import { siteConfig } from '@/lib/site-config'

/**
 * Dynamic Open Graph image per tool — Priority 9.
 *
 * URL: `/api/og?slug=<slug>` → 1200×630 PNG.
 *
 * Used by:
 *   - The per-tool `generateMetadata` `openGraph.images` field
 *   - Twitter card images
 *
 * Implementation: the image is generated by rendering an SVG string and
 * rasterizing it with `sharp` (already a project dependency, works on the
 * Vercel Node runtime). This replaces the previous `next/og` (Satori/Yoga/
 * WASM) implementation, which returned intermittent HTTP 500s in production
 * — Satori's `import.meta.url` WASM resolution is unreliable when bundled
 * for serverless Node functions, leaving every tool page with a broken
 * `og:image` (social crawlers show no preview card).
 *
 * `sharp` renders SVG→PNG deterministically with no WASM or edge-runtime
 * dependency, so the route is reliable on cold starts and under load.
 */

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const WIDTH = 1200
const HEIGHT = 630

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/** Truncate a string to a max length on a word boundary, adding an ellipsis. */
function truncate(text: string, max: number): string {
  if (text.length <= max) return text
  const slice = text.slice(0, max)
  const cut = slice.lastIndexOf(' ')
  return (cut > max * 0.6 ? slice.slice(0, cut) : slice) + '…'
}

function buildSvg(title: string, categoryLabel: string, categoryColor: string, tagline: string, footer: string): string {
  const safeTitle = escapeXml(truncate(title, 40))
  const safeTagline = escapeXml(truncate(tagline, 130))
  const safeFooter = escapeXml(footer)
  const safeCategory = escapeXml(categoryLabel)
  // Larger font for short titles, smaller for long ones.
  const titleSize = safeTitle.length > 24 ? 64 : 84
  return `<svg width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#0a0a0a"/>
      <stop offset="0.5" stop-color="#1a1a2e"/>
      <stop offset="1" stop-color="#16213e"/>
    </linearGradient>
    <linearGradient id="logo" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#6366f1"/>
      <stop offset="1" stop-color="#8b5cf6"/>
    </linearGradient>
  </defs>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#bg)"/>
  <g font-family="Arial, sans-serif" fill="#ffffff">
    <g>
      <rect x="64" y="64" width="56" height="56" rx="14" fill="url(#logo)"/>
      <text x="78" y="101" font-size="28" font-weight="800" text-anchor="middle">FL</text>
      <text x="136" y="100" font-size="26" font-weight="700" fill="#ffffff" opacity="0.95">${escapeXml(siteConfig.site.name || 'Fernandes Labs')}</text>
    </g>
    <rect x="${WIDTH - 64 - 20 - (safeCategory.length * 13)}" y="66" width="${20 + safeCategory.length * 13}" height="52" rx="26" fill="${categoryColor}"/>
    <text x="${WIDTH - 74 - (safeCategory.length * 6.5)}" y="100" font-size="20" font-weight="700" text-anchor="middle" letter-spacing="0.08em" text-transform="uppercase">${safeCategory}</text>
    <text x="64" y="${HEIGHT / 2 - 10}" font-size="${titleSize}" font-weight="800" letter-spacing="-0.02em">${safeTitle}</text>
    <text x="64" y="${HEIGHT / 2 + 70}" font-size="28" opacity="0.88">${safeTagline}</text>
    <line x1="64" y1="${HEIGHT - 104}" x2="${WIDTH - 64}" y2="${HEIGHT - 104}" stroke="#ffffff" stroke-opacity="0.15" stroke-width="1"/>
    <text x="64" y="${HEIGHT - 56}" font-size="22" opacity="0.75">${safeFooter}</text>
    <text x="${WIDTH - 64}" y="${HEIGHT - 56}" font-size="22" opacity="0.75" text-anchor="end">fernandeslabs.com</text>
  </g>
</svg>`
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const slug = searchParams.get('slug')
  const tool = slug ? getToolMeta(slug) : undefined

  const siteName = siteConfig.site.name || 'Fernandes Labs'
  const fallbackTagline =
    'Free online tools for developers, designers, and marketers.'

  if (!tool) {
    const svg = buildSvg(
      'Free Online Tools',
      'Tools',
      '#6366f1',
      fallbackTagline,
      `${siteName} · No sign-up · Privacy-first · Works offline`
    )
    const png = await sharp(Buffer.from(svg)).png().toBuffer()
    return new Response(new Uint8Array(png), {
      headers: {
        'content-type': 'image/png',
        'cache-control': 'public, max-age=86400, s-maxage=86400',
      },
    })
  }

  const cat = CATEGORY_META[tool.category as ToolCategory]
  const catLabel = cat?.label ?? 'Tool'
  const catColor = cat?.color ?? '#6366f1'
  const keywordText = (tool.keywords ?? []).slice(0, 4).join(' · ')

  const svg = buildSvg(
    tool.name,
    catLabel,
    catColor,
    tool.description,
    `${keywordText} · ${siteName}`
  )

  const png = await sharp(Buffer.from(svg)).png().toBuffer()
  return new Response(new Uint8Array(png), {
    headers: {
      'content-type': 'image/png',
      'cache-control': 'public, max-age=86400, s-maxage=86400',
    },
  })
}
