import sharp from 'sharp'
import { getToolMeta } from '@/lib/tools/tool-meta'
import { CATEGORY_META, type ToolCategory } from '@/lib/tools/types'
import { siteConfig } from '@/lib/site-config'
import { getBlogPost } from '@/lib/blog/posts'
import { blogCategoryColor } from '@/lib/blog/blog-utils'

/**
 * Dynamic Open Graph image per tool — Priority 9.
 *
 * URL: `/api/og?slug=<tool-slug>` → 1200×630 PNG (tool card)
 * URL: `/api/og?post=<post-slug>` → 1200×630 PNG (blog guide card)
 *
 * Used by:
 *   - The per-tool `generateMetadata` `openGraph.images` field
 *   - The per-post `generateMetadata` `openGraph.images` + `twitter.images`
 *   - Twitter card images
 *
 * Implementation: the image is generated by rendering an SVG string and
 * rasterizing it with `sharp` (already a project dependency, works on the
 * Vercel Node runtime). This replaces the previous `next/og` (Satori/Yoga/
 * WASM) implementation, which returned intermittent HTTP 500s in production
 * — Satori's `import.meta.url` WASM resolution is unreliable when bundled
 * for serverless Node functions, leaving every tool page with a broken
 * `og:image` (social crawlers show no preview card).
 *
 * `sharp` renders SVG→PNG deterministically with no WASM or edge-runtime
 * dependency, so the route is reliable on cold starts and under load.
 */

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const WIDTH = 1200
const HEIGHT = 630

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/** Truncate a string to a max length on a word boundary, adding an ellipsis. */
function truncate(text: string, max: number): string {
  if (text.length <= max) return text
  const slice = text.slice(0, max)
  const cut = slice.lastIndexOf(' ')
  return (cut > max * 0.6 ? slice.slice(0, cut) : slice) + '…'
}

/**
 * Approximate rendered width of bold Arial text — used to pick a font size
 * that fits the canvas instead of letting long post titles overflow the edge
 * (avg advance for Arial Bold ≈ 0.58 × font-size).
 */
const AVAIL_WIDTH = WIDTH - 128

function fontSizeToFit(text: string, cap: number, floor = 28): number {
  const fit = Math.floor(AVAIL_WIDTH / (0.58 * Math.max(text.length, 1)))
  return Math.max(floor, Math.min(cap, fit))
}

/**
 * Split a title into 1–2 lines at the word boundary that balances line
 * lengths, so long guide titles wrap instead of being chopped by the canvas.
 */
function splitTitleLines(title: string, maxLen: number): string[] {
  const t = truncate(title, maxLen)
  if (t.length <= 26) return [t]
  const words = t.split(' ')
  let best: [string, string] = [t, '']
  let bestDiff = Infinity
  for (let i = 1; i < words.length; i++) {
    const a = words.slice(0, i).join(' ')
    const b = words.slice(i).join(' ')
    const diff = Math.abs(a.length - b.length)
    if (b.length > 0 && diff < bestDiff) {
      bestDiff = diff
      best = [a, b]
    }
  }
  return best[1] ? best : [t]
}

/**
 * Convert oklch() to sRGB hex. CATEGORY_META colors are Tailwind v4 oklch
 * strings — valid in CSS, but NOT supported by librsvg/sharp SVG rasterization
 * (an oklch fill silently renders as a solid white shape). Every color that
 * enters the SVG must pass through svgColor() first.
 */
function oklchToHex(color: string): string | null {
  const m = color.match(/oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)/i)
  if (!m) return null
  const L = parseFloat(m[1])
  const C = parseFloat(m[2])
  const H = (parseFloat(m[3]) * Math.PI) / 180
  const a = C * Math.cos(H)
  const b = C * Math.sin(H)
  // OKLab → LMS³ → linear sRGB (Björn Ottosson's reference matrices).
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b
  const s_ = L - 0.0894841775 * a - 1.291485548 * b
  const l = l_ * l_ * l_
  const mm = m_ * m_ * m_
  const s = s_ * s_ * s_
  let r = 4.0767416621 * l - 3.3077115913 * mm + 0.2309699292 * s
  let g = -1.2684380046 * l + 2.6097574011 * mm - 0.3413193965 * s
  let bl = -0.0041960863 * l - 0.7034186147 * mm + 1.707614701 * s
  const gamma = (c: number) =>
    c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055
  const enc = (c: number) =>
    Math.round(Math.min(255, Math.max(0, gamma(c) * 255)))
  const hex = (n: number) => n.toString(16).padStart(2, '0')
  return `#${hex(enc(r))}${hex(enc(g))}${hex(enc(bl))}`
}

function svgColor(color: string | undefined, fallback = '#6366f1'): string {
  if (!color) return fallback
  if (color.startsWith('oklch')) return oklchToHex(color) ?? fallback
  return color
}

function buildSvg(
  title: string,
  categoryLabel: string,
  categoryColor: string,
  tagline: string,
  footer: string,
  maxTitleLen = 40
): string {
  const safeCategory = escapeXml(categoryLabel)
  const safeFooter = escapeXml(footer)
  // Title — up to 2 lines, font sized so the longest line fits the canvas.
  const titleLines = splitTitleLines(title, maxTitleLen)
  const longestLine = titleLines.reduce((a, b) => (b.length > a.length ? b : a), '')
  const titleSize =
    titleLines.length === 1
      ? longestLine.length > 24
        ? 64
        : 84
      : fontSizeToFit(longestLine, 64)
  // Tagline — sized to fit too (long excerpts shrink to stay on-canvas).
  const taglineText = truncate(tagline, 100)
  const taglineSize = fontSizeToFit(taglineText, 28, 16)
  const safeTagline = escapeXml(taglineText)

  // Vertical rhythm: center the title block; keep ≥48px gap before the tagline.
  const titleBlockH = (titleLines.length - 1) * (titleSize + 14)
  const titleY = HEIGHT / 2 - 10 + (titleLines.length > 1 ? titleBlockH / 2 : 0)
  const taglineY = titleY + titleBlockH + 64
  const titleText = titleLines
    .map(
      (line, i) =>
        `<text x="64" y="${titleY + i * (titleSize + 14)}" font-size="${titleSize}" font-weight="800" letter-spacing="-0.02em">${escapeXml(line)}</text>`
    )
    .join('\n    ')

  return `<svg width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#0a0a0a"/>
      <stop offset="0.5" stop-color="#1a1a2e"/>
      <stop offset="1" stop-color="#16213e"/>
    </linearGradient>
    <linearGradient id="logo" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#6366f1"/>
      <stop offset="1" stop-color="#8b5cf6"/>
    </linearGradient>
  </defs>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#bg)"/>
  <g font-family="Arial, sans-serif" fill="#ffffff">
    <g>
      <rect x="64" y="64" width="56" height="56" rx="14" fill="url(#logo)"/>
      <text x="78" y="101" font-size="28" font-weight="800" text-anchor="middle">FL</text>
      <text x="136" y="100" font-size="26" font-weight="700" fill="#ffffff" opacity="0.95">${escapeXml(siteConfig.site.name || 'Fernandes Labs')}</text>
    </g>
    <rect x="${WIDTH - 64 - 20 - (safeCategory.length * 13)}" y="66" width="${20 + safeCategory.length * 13}" height="52" rx="26" fill="${svgColor(categoryColor)}"/>
    <text x="${WIDTH - 74 - (safeCategory.length * 6.5)}" y="100" font-size="20" font-weight="700" text-anchor="middle" letter-spacing="0.08em" text-transform="uppercase">${safeCategory}</text>
    ${titleText}
    <text x="64" y="${taglineY}" font-size="${taglineSize}" opacity="0.88">${safeTagline}</text>
    <line x1="64" y1="${HEIGHT - 104}" x2="${WIDTH - 64}" y2="${HEIGHT - 104}" stroke="#ffffff" stroke-opacity="0.15" stroke-width="1"/>
    <text x="64" y="${HEIGHT - 56}" font-size="22" opacity="0.75">${safeFooter}</text>
    <text x="${WIDTH - 64}" y="${HEIGHT - 56}" font-size="22" opacity="0.75" text-anchor="end">fernandeslabs.com</text>
  </g>
</svg>`
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const toolSlug = searchParams.get('slug')
  const postSlug = searchParams.get('post')
  const tool = toolSlug ? getToolMeta(toolSlug) : undefined

  const siteName = siteConfig.site.name || 'Fernandes Labs'
  const fallbackTagline =
    'Free online tools for developers, designers, and marketers.'

  // Blog guide card — the guide's own title and category color, so shares on
  // X/LinkedIn/WhatsApp preview the ARTICLE, not the first related tool.
  const post = postSlug ? getBlogPost(postSlug) : undefined
  if (post) {
    const svg = buildSvg(
      post.title,
      post.category,
      blogCategoryColor(post.category),
      post.description,
      `${post.date} · ${siteName} Blog · Free guides`,
      48 // post titles run longer than tool names — allow 2 lines of smaller text
    )
    const png = await sharp(Buffer.from(svg)).png().toBuffer()
    return new Response(new Uint8Array(png), {
      headers: {
        'content-type': 'image/png',
        'cache-control': 'public, max-age=86400, s-maxage=86400',
      },
    })
  }

  if (!tool) {
    const svg = buildSvg(
      'Free Online Tools',
      'Tools',
      '#6366f1',
      fallbackTagline,
      `${siteName} · No sign-up · Privacy-first · Works offline`
    )
    const png = await sharp(Buffer.from(svg)).png().toBuffer()
    return new Response(new Uint8Array(png), {
      headers: {
        'content-type': 'image/png',
        'cache-control': 'public, max-age=86400, s-maxage=86400',
      },
    })
  }

  const cat = CATEGORY_META[tool.category as ToolCategory]
  const catLabel = cat?.label ?? 'Tool'
  const catColor = cat?.color ?? '#6366f1'
  const keywordText = (tool.keywords ?? []).slice(0, 4).join(' · ')

  const svg = buildSvg(
    tool.name,
    catLabel,
    catColor,
    tool.description,
    `${keywordText} · ${siteName}`
  )

  const png = await sharp(Buffer.from(svg)).png().toBuffer()
  return new Response(new Uint8Array(png), {
    headers: {
      'content-type': 'image/png',
      'cache-control': 'public, max-age=86400, s-maxage=86400',
    },
  })
}
